#define COMBO_ONLY_FROM_LAYER 0
#define ONESHOT_TAP_TOGGLE 2

#define ENABLE_COMPILE_KEYCODE

#define MOUSEKEY_INERTIA
#define MOUSEKEY_DELAY 150
#define MOUSEKEY_INTERVAL 16
#define MOUSEKEY_MAX_SPEED 32
#define MOUSEKEY_TIME_TO_MAX 32
#define MOUSEKEY_FRICTION 24
#define MOUSEKEY_MOVE_DELTA 1

#define SWAP_HANDS_ENABLE = YES
