#define COMBO_ONLY_FROM_LAYER 0
#define ONESHOT_TAP_TOGGLE 2

#define ENABLE_COMPILE_KEYCODE

#define MOUSEKEY_INERTIA
#define MOUSEKEY_DELAY 10
#define MOUSEKEY_INTERVAL 16
#define MOUSEKEY_MAX_SPEED 16
#define MOUSEKEY_TIME_TO_MAX 32
#define MOUSEKEY_FRICTION 24
#define MOUSEKEY_MOVE_DELTA 1
#define MOUSEKEY_WHEEL_DELTA 16

#define SWAP_HANDS_ENABLE = YES

#define LEADER_PER_KEY_TIMING
#define LEADER_TIMEOUT 100
#define LEADER_NO_TIMEOUT

//#define SPLIT_LAYER_STATE_ENABLE
